### ISSUE TITLE
Walking on first playthrough

### ISSUE THREAD

**Issue by TristonPlummer** [Entrana/EntranaBugs#10]
Steps to reproduce:

1. Delete the local cache.
2. Start the beta game client.
3. Login
4. Try and walk anywhere, client should crash. Is fixed on relog.

**Comment by Farmict** [comment]
Solved on last client push

**Comment by Farmict** [comment]
Fixed, was a sprite error: sprite not downloaded yet. Made it check if sprite exists to show map flag
