### ISSUE TITLE
Game crashes often in varrock

### ISSUE THREAD

**Issue by Zachownsall** [Entrana/EntranaBugs#17]
Unsure of what causes it. Thought it was toggling run, but it seems to just do it now if I stay inside varrock with any account. The account will be fine and walking around then the game will crash. Happening around range shop. I have used tele runes to get there, ::tele. and walked from lumbridge. Game always crashes in varrock

**Comment by TristonPlummer** [comment]
```
Error: Class3_Sub13_Sub13.handleMainGame:408 client.mainLoop:2322 GameShell.method36:259 GameShell.run:362 java.lang.Thread.run:748 | java.lang.NullPointerException
error_game_crash
Shutdown complete - clean:true```
