### ISSUE TITLE
Pipe, stepping stones and stairs in brimhaven dungeon dont work

### ISSUE THREAD

**Issue by Zachownsall** [Entrana/EntranaBugs#20]
https://gyazo.com/5c30ea08312177945cbfdfd9e6175665
https://gyazo.com/b0d2d35fb5d645a6bf658797668bbfd4
https://gyazo.com/333e1147b8ec0e914da18282f5f51b57

**Comment by TristonPlummer** [comment]
Possible issue with landscape parsing and rendering tiles over objects. Will look into it.

**Comment by Farmict** [comment]
Fixed in new client
