### ISSUE TITLE
Max cash for your entire account is 2.1b - details inside

### ISSUE THREAD

**Issue by Zachownsall** [Entrana/EntranaBugs#26]
If you have a max cash stack in you bank and take out 1 coin and drop it and then try to pick up a cash stack of say 100m that 100m will turn into 1 gp meaning 99,999,999 coins vanish

I just recreated it without the same results, will update shortly

seems to only be for spawned cash which makes sense
Okay, steps to recreate it -
Have max cash in bank. 
Have money on ground available to pick up.
Remove 1 coin
Drop 1 coin
Pick up any cash stack larger than 1 coin
Only 1 coin shows up in inventory erasing the rest of it

**Comment by Farmict** [comment]
Seems to work okay now.

What the new issue is, when picking up the "one coin", it'll remove the big stack but still show one coin on the ground. The one coin being the "big stack".

Resolved as I don't think this issue will reoccur often if at all, and it seems like you can hold money properly now.
