### ISSUE TITLE
Trading fucks shit up

### ISSUE THREAD

**Issue by Zachownsall** [Entrana/EntranaBugs#53]
How to recreate -

Player 1 trades player 2
player 2 trades player 1 (note player 2 cannot click on accept trade. they must physically trade player 1)
In trade window player 1 puts up items that want to be traded and clicks accept
Player 2 clicks accept

This is where the problem lies -
Player 2 sees the second trade screen that is COMPLETELY empty even if something was traded.
Player 1 still sees the 'waiting for other player' at the bottom of the trade window

If player 1 accepts again he sees the same thing as player 2 (the second trade screen that is COMPLETELY empty even if something was traded.)

When player 2 clicks accept on the second trade window all the items in the trade are put into his inventory, but the 2nd trade window remains on screen.

When both players try to move after the trade window has been exited they are stuck and the only way to move is by attacking an npc or by following another player.

BOTH PLAYERS CANNOT MOVE EVEN AFTER CLOSING CLIENT AND RELOGGING

https://gyazo.com/b9a74f2088d2ed2cdebed5f62915de92

After relogging you do not have the proper options on players
https://gyazo.com/7ce2ce805f5ba69d525bd3e800583316

**Comment by Farmict** [comment]
Appears to be fixed
