### ISSUE TITLE
Combat doesn't show properly

### ISSUE THREAD

**Issue by Zachownsall** [Entrana/EntranaBugs#61]
https://gyazo.com/4f01d548598797e5447f2c2a7d5654eb
https://gyazo.com/09a8867d6cf9d36df895ce7e577ed07c

**Comment by Indominuz** [comment]
M8, you're gonna need some info? Lol

**Comment by Farmict** [comment]
This is a player appearance issue

**Comment by Farmict** [comment]
Fixed, setting a level wouldn't flag a combat level refresh.
