### ISSUE TITLE
G.E 'Sets'

### ISSUE THREAD

**Issue by Indominuz** [Entrana/EntranaBugs#62]
When selecting the 'Sets' feature at G.E, you run away from the clerk as if she just killed someone, and then you run to a spot in the castle.

https://gyazo.com/ff477f29f75e4edb99f6b33fab106012

**Comment by Farmict** [comment]
@TristonPlummer 

This is related to NPC option 4 being "drop"

**Comment by Farmict** [comment]
Fixed in new client
