### ISSUE TITLE
Coal...?

### ISSUE THREAD

**Issue by Indominuz** [Entrana/EntranaBugs#68]
Went into wildy, mined 4 mithril ore, 1 addy, and 3 coal.

Spawned 10 coal (id = 453), and was using "Superheat Item"

Was able to create 3 mithril bars, but for some reason it was telling me "You do not have the required items to make this bar." afterwards. 

It seems to not be registering the spawned coal as usable coal for smithing, tried all 3 coal id's (453, 454 and 25630, which didn't work).

I'm guessing there's a confusion with id's for coal.

**Comment by Indominuz** [comment]
After I wrote this, i farmed 3 more coal (using the wildy rocks) and it said I got coal but, it's invisible in my inventory. Yet I can still superheat with it (it being invisible coal)

**Comment by Indominuz** [comment]
Also, Edgeville furnance is unusable due to requiring varrock diaries tasks.

**Comment by Farmict** [comment]
Pending SwitchSlot packet

**Comment by Farmict** [comment]
Solved by @TristonPlummer
