### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by ramakazi** [Entrana/EntranaBugs#75]
The top left emote, "Yes", does nothing. The 2nd emote to the top left, "No", performs what is supposed to be "Yes" emote. All emotes from there on are 1 off the same as yes and no.

**Comment by Indominuz** [comment]
"skillcape emote can be unlocked by completing the halloween event"

**Comment by TristonPlummer** [comment]
Mismatch between OSRS emote buttons and the 530 definitions.

**Comment by Farmict** [comment]
Fixed in new client
