### ISSUE TITLE
Some shops oddly stocked

### ISSUE THREAD

**Issue by ramakazi** [Entrana/EntranaBugs#77]
Gem trader in Al-Kharid infinite stocked gem shop.

Ali Morrisane shop is different from RuneScape as well, but not by much (still some are randomly 31 while others 30 etc) and there is an issue in the title of his shop menu, ends in #runes for some reason. Probably more messed up shops, will update if I find any

**Comment by Farmict** [comment]
Fixed infinity symbol, shop stocks are not a priority

Fixed #runes text
