### ISSUE TITLE
Town Crier dialogue errors

### ISSUE THREAD

**Issue by ramakazi** [Entrana/EntranaBugs#78]
Tons of inconsistencies and typos, only posting this cuz I'm not sure there'd ever be a reason to look at town crier ever again. Sometimes it's P-Mods, sometimes P_Mods, "get scamme dby another player", some words missing the last letter if they're the final word in the line. The last one could be an issue with all dialogue and not just typos (account -> accoun, report -> repor, etc)

**Comment by TristonPlummer** [comment]
`plugin.dialogue.TownCrierDialogue`

Seems to just be typo related. Quality of life fix, not overly important.

**Comment by Farmict** [comment]
Did a little clean up, will look into dialogues more as we move along
