### ISSUE TITLE
KBD continued (and more)

### ISSUE THREAD

**Issue by Indominuz** [Entrana/EntranaBugs#81]
DFS and ADS work correctly - blocks most of the breath.
Antifire potion doesn't work at all and only lasts roughly 15 - 30 seconds,
neither does antipoison (at all).
KBD also hits hard through prayer (tried both Magic & Melee prot)
Can't attack KBD unless you use Auto-Retal (Attack feature's broken)

**Comment by Farmict** [comment]
Solved all but attack, need to dig into this more.

Antifire was caused by "Dev Mode" being active and anti-fire lasting 50 ticks instead of 600
