### ISSUE TITLE
Dialogue issue

### ISSUE THREAD

**Issue by ramakazi** [Entrana/EntranaBugs#84]
Any helmet equipped removes your head from dialogues (some hats will show only your beard)

Partyhat doesn't remove your head but the partyhat isnt shown in dialogue.

Also just tested with earmuffs and client crashed.

**Comment by ramakazi** [comment]
quick update: restarted client and tried again with earmuffs on, game crashed again.

**Comment by ramakazi** [comment]
final update on this: face mask also crashes game. nose peg/spiny helm/ black mask are ok (but nose peg doesnt show, and spiny helm/black mask remove your head from dialogue)

**Comment by Farmict** [comment]
Closed, will be solved upon next update
