### ISSUE TITLE
All TzHaar npcs are animated guthix cape imbued from osrs

### ISSUE THREAD

**Issue by ramakazi** [Entrana/EntranaBugs#87]
the banker is wearing guardian boots too (he is also a guthix cape imbued)

**Comment by ramakazi** [comment]
Update: some of them are actually Zamorak cape imbued as well, and others are animated granite hammers, wearing slayer gloves on their feet.

**Comment by TristonPlummer** [comment]
OSRS Models overwriting 530 Models @Farmict ?

**Comment by Farmict** [comment]
Fixed

TODO: Add OSRS models to their own separate index, I guess Jagex thought it was a good idea to overwrite some models for new items instead of making new ones
