### ISSUE TITLE
Fight Caves is untextured and crashes client when you enter through cave entrance in TzHaar city

### ISSUE THREAD

**Issue by ramakazi** [Entrana/EntranaBugs#89]

**Comment by ramakazi** [comment]
random extra add here since it doesnt deserve its own issue, but if it matters; viewing orb in fight pits does not work

**Comment by Farmict** [comment]
Fixed, viewing orb unsupported at this time

**Comment by Farmict** [comment]
TzHaar needs work, and Dynamic Regions
